### ISSUE TITLE
Metric / Imperial unit selector

### ISSUE THREAD

**Issue by marcelltoth** [zsofiaflorek/weather-app#1]
**As a** user from a country that uses the imperial system,
**I want** to be able to view the temperature in F **so that** I can interpret it.

Currently we just display data as is, likely a UK format. As a first step towards internalization we would like to add a C/F selector.

### Acceptance Criteria

1. There is a C/F selector in the top right corner of the summary panel like this: ![image](https://user-images.githubusercontent.com/543372/121656141-7961de80-ca9f-11eb-9acd-29cb7b5ccb59.png)

2. For a new user, the selector starts in a *C selected* state.
3. When the selector buttons are clicked, the clicked button moves into a *selected* state.
4. The summary and daily temperatures are always displayed in units according to the current *selected* state of the C/F selector.
3. *Bonus, optional:* The selected temperature unit is persisted across visits to the site.

Please also note:

- Requirement 1 contradicts somewhat with the Figma designs. The written requirement takes precedence.

**Comment by zsofiaflorek** [comment]
Resolved by #4
